import type { Metadata } from "next";
import Head from "next/head";

export const metadata: Metadata = {
    title: "Pulse Id",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <Head>
                <link rel="preconnect" href="https://fonts.gstatic.com" />
            </Head>
            <body>{children}</body>
        </html>
    );
}
